version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 11
      MYSQL_DATABASE: mindmapdb
    ports:
      - "3306:3306"

  mindmap-be:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - efk-stack_default
      - default
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: admin
      APP_DSN: 'root:11@tcp(db:3306)/mindmapdb?parseTime=true'
    depends_on:
      - db

volumes:
  mysql:
  
networks:
  default:
    driver: bridge
  efk-stack_default:
    external: true